name: Deploy Cobalt

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cobalt Repository
        uses: actions/checkout@v4
        with:
          repository: imputnet/cobalt

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Install Root Dependencies
        run: pnpm install

      - name: Patch Configuration Files
        working-directory: ./web
        run: |
          sed -i 's|https://api.cobalt.tools|https://cobalt-api.jacob.com.hk|g' src/lib/env.ts
          
          sed -i 's|"font-src": \["self"\]|"font-src": ["self", "https://cdn.jsdelivr.net"]|g' svelte.config.js
          sed -i 's|"style-src": \["self", "unsafe-inline"\]|"style-src": ["self", "unsafe-inline", "https://cdn.jsdelivr.net"]|g' svelte.config.js

      - name: Install Web Dependencies & Build
        working-directory: ./web
        env:
          WEB_DEFAULT_API: "https://cobalt-api.jacob.com.hk"
        run: |
          pnpm install
          pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
